In [66]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [67]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
my = np.arange(30)

In [69]:
type(my)

numpy.ndarray

In [70]:
my

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [71]:
my.max()

29

In [72]:
my.mean()

14.5

In [73]:
np.math.sqrt(45)

6.708203932499369

In [74]:
my[-1]

29

In [75]:
ser=pd.Series([1,2,3,4],['AUS','IND','USA','UK'])

In [76]:
ser

AUS    1
IND    2
USA    3
UK     4
dtype: int64

In [77]:
np.random.seed(101)

In [78]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [79]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [80]:
me=df['Y']

In [81]:
me.mean()

0.4522872041305265

NUMPY only handles single datatype array either integer or float or strings
one dimensional array 2d array 3d rray(we should know hw to access it)
we cant delete an element in nd array , where it will disturb its matrix lets us say 2x3

# Boolean operations

In [82]:
ar=np.random.randn(1,10)

In [83]:
ar

array([[ 0.30266545,  1.69372293, -1.70608593, -1.15911942, -0.13484072,
         0.39052784,  0.16690464,  0.18450186,  0.80770591,  0.07295968]])

In [84]:
ar1=np.array([2,5,4,3,6,4,7,3,4,9])

In [85]:
ar1>ar

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [86]:
ar2=ar1+ar

In [87]:
ar2

array([[2.30266545, 6.69372293, 2.29391407, 1.84088058, 5.86515928,
        4.39052784, 7.16690464, 3.18450186, 4.80770591, 9.07295968]])