In [2]:
seq = [1,2,3,4,5]

In [10]:
list(filter(lambda num:num%2 == 0,seq))


[2, 4]

In [11]:
list = [1,2,3,4,4,5]
import numpy as np 
ar =np.array(list)


In [12]:
ar

array([1, 2, 3, 4, 4, 5])

In [13]:
print(ar)

[1 2 3 4 4 5]


In [14]:
np

<module 'numpy' from 'C:\\Users\\HP\\Anaconda3.5.1\\lib\\site-packages\\numpy\\__init__.py'>

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])